# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=50)),
                ('c_faculty_name', models.CharField(max_length=50)),
                ('c_duration', models.IntegerField()),
                ('c_stating_date', models.DateField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Query_base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254)),
                ('Message', models.TextField(max_length=500)),
                ('Mobile', models.IntegerField()),
            ],
        ),
    ]
