# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-07-31 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=50)),
                ('Last_Name', models.CharField(max_length=50)),
                ('Father_Name', models.CharField(max_length=50)),
                ('Email', models.EmailField(default=None, max_length=254)),
                ('Mobile', models.PositiveIntegerField()),
                ('State', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Qualification', models.CharField(max_length=50)),
            ],
        ),
    ]
